name: Release

on: 
  push:
    branches:
      - release

jobs:

  create-release:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Release Notes
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-message: 'chore: release {version}'
          skip-version-file: 'true'
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          draft: true
          prerelease: false

      - name: Build Release
        uses: crazy-max/ghaction-xgo@v1
        with:
          xgo_version: latest
          go_version: "1.14.x"
          dest: build
          prefix: antidot
          targets: windows/*,linux/*,darwin/*
          v: true
          ldflags: -s -w -X 'main.version=${{ steps.changelog.outputs.tag }}'
          buildmode: default

      - name: Upload Releases
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/*

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Release ${{ steps.changelog.outputs.tag }}
          body: |
            Automatic release of version ${{ steps.changelog.outputs.tag }}
            Draft release: ${{ steps.create_release.outputs.html_url }}
          reviewers: doron-cohen
