name: Release

on:
  workflow_dispatch:

jobs:

  create-release:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Generate Release Notes
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-user-name: ${{ github.actor }}
          git-user-email: ${{ github.actor }}@users.noreply.github.com
          git-message: 'chore: release {version}'
          skip-version-file: 'true'

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          draft: true
          prerelease: false

      - name: Build Release
        uses: crazy-max/ghaction-xgo@v1
        with:
          xgo_version: latest
          go_version: "1.14.x"
          dest: build
          prefix: antidot
          targets: linux/386,linux/amd64,darwin/amd64
          v: false
          ldflags: -s -w -X 'main.version=${{ steps.changelog.outputs.tag }}'
          buildmode: default

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/antidot-*
          tag: ${{ steps.changelog.outputs.tag }}
          overwrite: true
          file_glob: true
